services:
  nginx:
    build: .
    container_name: www_nginx
    restart: unless-stopped


  portfolio_daniwebtutorial_webui:
    image: davideponzini/daniwebtutorial_webui
    container_name: daniwebtutorial_webui
    restart: unless-stopped
    ports:
      - "10000:80"

  portfolio_daniwebtutorial_db:
    image: davideponzini/daniwebtutorial_db
    container_name: daniwebtutorial_db
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: dani_web_tutorial
      MYSQL_USER: daniadmin
      MYSQL_PASSWORD: password
    volumes:
      - daniwebtutorial_mysql_data:/var/lib/mysql

volumes:
  daniwebtutorial_mysql_data:
