services:
  nginx_prod:
    build: .
    container_name: www_nginx_prod
    restart: unless-stopped
    ports:
      - "10000:80"
    profiles:
      - prod

  nginx_dev:
    build: ./nginx
    container_name: www_nginx_dev
    restart: unless-stopped
    ports:
      - "10000:80"
    profiles:
      - dev

  server:
    build: ./server
    container_name: www_server
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - MAX_CONTENT_LENGTH=20971520
    env_file:
      - server/.env

  db:
    build: ./db
    container_name: www_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - www_db_data:/var/lib/postgresql/data

  webui:
    build: ./webui
    container_name: www_webui
    restart: unless-stopped
    ports:
      - "3000:3000"
    profiles:
      - dev

  portfolio_daniwebtutorial_webui:
    image: davideponzini/daniwebtutorial_webui
    container_name: www_daniwebtutorial_webui
    restart: unless-stopped
    environment:
      DB_HOST: portfolio_daniwebtutorial_db
      DB_PORT: 3306
      DB_NAME: dani_web_tutorial
      DB_USER: daniadmin
      DB_PASSWORD: password
    ports:
      - "10010:80"

  portfolio_daniwebtutorial_db:
    image: davideponzini/daniwebtutorial_db
    container_name: www_daniwebtutorial_db
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: dani_web_tutorial
      MYSQL_USER: daniadmin
      MYSQL_PASSWORD: password
    volumes:
      - www_daniwebtutorial_mysql_data:/var/lib/mysql

  utils_apache:
    image: davideponzini/www_apache_utils
    container_name: www_apache_utils
    restart: unless-stopped
    ports:
      - "10011:80"

volumes:
  www_daniwebtutorial_mysql_data:
  www_db_data:
