START TRANSACTION;

DROP DATABASE IF EXISTS www;

CREATE DATABASE www;
GRANT SELECT, INSERT, UPDATE, DELETE ON www.* TO 'dba'@'localhost';

CREATE TABLE www.redirects (
    name VARCHAR(100) PRIMARY KEY NOT NULL,
    target TEXT NOT NULL
);

COMMIT;
